### ISSUE TITLE
Highlighting for Scala

### ISSUE THREAD

**Issue by spmp** [silvestreh/atom-material-syntax-dark#14]
Can you please provide support for Scala?

Cheers

**Comment by silvestreh** [comment]
What doesn't look good for Scala?

**Comment by spmp** [comment]
My bad, it must have been an Atom issue. looks great thank you!

**Comment by silvestreh** [comment]
No problem, glad you sorted it out!

Just to leave a little piece of advice to whomever finds this issue in the future: If the language you're using isn't being correctly colored, it might be due to a missing language package. For example, React's JSX looks bad unless you install a third party package like [`language-babel`](https://atom.io/packages/language-babel).
